baseURL = "https://http-testing-r.netlify.app/"
languageCode = "en-US"
defaultContentLanguage = "en"
title = "GET better at testing your R package!"
enableEmoji = true
pygmentsUseClasses=true
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$", "index\\.html", '\.knit\.md$', '\.utf8\.md$']

[module]
  [[module.imports]]
    path = "github.com/matcornic/hugo-theme-learn"
  [[module.imports]]
    path = "github.com/dzello/reveal-hugo"
    
[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true


[outputs]
home = [ "HTML", "RSS", "JSON"]

[Languages]
[Languages.en]
title = "useR! 2021 tutorial"
weight = 1
languageName = "English"

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/maelle/http-testing-course"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Credits"
url = "/credits"
weight = 30

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-certificate'></i> CC-BY Licence"
url = "https://creativecommons.org/licenses/by/4.0/"
weight = 40

[params]
  editURL = "https://github.com/maelle/http-testing-course/edit/main/content/"
  description = "GET better at testing your R package!"
  author = "Maëlle Salmon"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "mine"



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
[params.reveal_hugo]
custom_theme = "reveal-hugo/themes/sunblind.css"
load_default_plugins = true
highlight_theme = "color-brewer"
margin = "0.2"
transition = "slide"
transition_speed = "fast"
