---
title: Demo
weight: 2
output: hugodown::md_document
---


## System setup

Check where we all are compared to [the instructions](/part-1/system-prep).

## Discover our example package

* For info, [R-universe API docs](https://ggseg.r-universe.dev/ui#api).

* Generate a repository from [the template repository](https://github.com/maelle/applepie)[^applepie]

* `usethis::create_from_github("YOURUSERNAME/applepie")`.

* Open RStudio project.

* Optional: look for occurrences of "maelle" (README, DESCRIPTION) and replace them with your username.

* `devtools::load_all()`

* `get_packages("ggseg")`

* `devtools::check()`

* `usethis::use_mit_license()`

* `devtools::check()`

## Add cute little tests

* `usethis::use_testthat()`

* `usethis::use_test("packages")` ([testthat expectations](https://testthat.r-lib.org/reference/index.html))

* `devtools::test()` or test button on the file or test via the build panel. Possibility to set keyboard shortcuts.

* `covr::report()`.

* Add a new function `use_r("maintainers")`, `use_package("withr")`, `use_package("tibble")`.

* `covr::report()`.

## Add continuous integration

* `usethis::use_github_action_check_standard()`

* `use_coverage()`

* `usethis::use_github_action("test-coverage-pak")`

* BACK TO SLIDES.

## Start using vcr

* `vcr::use_vcr()`

* Read example test, delete it.

* Insert `vcr::use_cassette("packages")` in a test. Have a look at the files added. If this were not an online tutorial, turn off wifi and run the test again, it works!

* BACK TO SLIDES.

[^applepie]: Why applepie? `r hugodown::embed_tweet("1397948070378225670")`