---
title: Snippets
weight: 1
hidden: true
chapter: false
disableToc: false
output: hugodown::md_document
---

For copy-pasting during demos.

## Tests for `get_packages()`

```{r eval=FALSE}
test_that("get_packages() works", {
  vcr::use_cassette("packages", {
    pkgs <- get_packages("maelle")
  })
  expect_vector(pkgs, character())
})
```

with automatic cassette.

```{r eval=FALSE}

test_that("get_packages() error", {
  vcr::skip_if_vcr_off()
  vcr::use_cassette("packages-error", {
    expect_error(get_packages("maelle"), "take off")
  })
})
```

with cassette

```yaml
http_interactions:
- request:
    method: get
    uri: https://maelle.r-universe.dev/packages
    body:
      encoding: ''
      string: ''
    headers:
      Accept: application/json, text/xml, application/xml, */*
  response:
    status:
      status_code: 502
  recorded_at: 2021-05-27 13:44:41 GMT
  recorded_with: vcr/0.6.5.93, webmockr/0.8.0

```

```{r eval=FALSE}
test_that("get_packages() retries", {
  vcr::skip_if_vcr_off()
  vcr::use_cassette("packages-retry", {
    expect_message(pkgs <- get_packages("maelle"), "try")
  })
  expect_vector(pkgs, character())
})

```

with cassette

```yaml
http_interactions:
- request:
    method: get
    uri: https://maelle.r-universe.dev/packages
    body:
      encoding: ''
      string: ''
    headers:
      Accept: application/json, text/xml, application/xml, */*
  response:
    status:
      status_code: 502
- request:
    method: get
    uri: https://maelle.r-universe.dev/packages
    body:
      encoding: ''
      string: ''
    headers:
      Accept: application/json, text/xml, application/xml, */*
  response:
    status:
      status_code: 200
      category: Success
      reason: OK
      message: 'Success: (200) OK'
    headers:
      server: nginx/1.18.0
      date: Thu, 27 May 2021 13:44:41 GMT
      content-type: application/json; charset=utf-8
      content-length: '180'
      connection: keep-alive
      x-powered-by: Express
      access-control-allow-origin: '*'
      etag: W/"b4-gNSpI8aK0mIGDXSgCPEFSExATo0"
    body:
      encoding: UTF-8
      file: no
      string: |-
        [
          "cransays",
          "crul",
          "goodpress",
          "hugodown",
          "lockedatapkg",
          "riem",
          "roblog",
          "rodev",
          "rtimicropem",
          "slugify",
          "tinkr",
          "vcr",
          "webmockr",
          "xml2"
        ]
  recorded_at: 2021-05-27 13:44:41 GMT
  recorded_with: vcr/0.6.5.93, webmockr/0.8.0

```

## `get_maintainers()`

```{r eval=FALSE}
#' Maintainers
#'
#' @inheritParams get_packages
#'
#' @return A character vector.
#' @export
#'
#' @examples
#' get_maintainers("ggseg")
get_maintainers <- function(universe) {
  url <- sprintf("https://%s.r-universe.dev/stats/maintainers", universe)
  resp <- httr::GET(url)
  httr::stop_for_status(resp)
  content <- httr::content(resp)
  temp_file <- withr::local_tempfile()
  writeLines(content, temp_file)
  maintainers <- jsonlite::stream_in(file(temp_file), verbose = FALSE)
  tibble::as_tibble(maintainers)
}
```

## `get_packages2()`


```{r eval=FALSE}
#' Packages
#'
#' @param universe universe to query
#'
#' @return A character vector.
#' @export
#'
#' @examples
#' \dontrun{
#' get_packages2("ropensci")
#'}
get_packages2 <- function(universe) {
  url <- sprintf("https://%s.r-universe.dev/packages", universe)
  token <- Sys.getenv("SECRET_PLANET_TOKEN")
  if (!nzchar(token)) {
    stop("Token for packages not found. See ?get_packages2")
  }

  resp <- httr::RETRY("GET", url,
    httr::add_headers("Authorization" = paste("token", token)))
  httr::stop_for_status(resp, "take off")
  content <- httr::content(resp)
  unlist(content)
}
```

vcr config in `tests/testthat/setup-applepie.R`

```{r eval=FALSE}
library("vcr") # *Required* as vcr is set up on loading
invisible(vcr::vcr_configure(
  dir = vcr::vcr_test_path("fixtures"),
  filter_request_headers = list(Authorization = "not-my-secret-hehe")
))
vcr::check_cassette_names()
if (!nzchar(Sys.getenv("SECRET_PLANET_TOKEN"))) {
  Sys.setenv("SECRET_PLANET_TOKEN" = "foobar")
}
```

Test itself

## Scheduled run

```yaml
# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    - main
  schedule:
    - cron:  '0 12 * * *'

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
          - {os: ubuntu-20.04,   r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest", http-user-agent: "R/4.1.0 (ubuntu-20.04) R (4.1.0 x86_64-pc-linux-gnu x86_64 linux-gnu) on GitHub Actions" }

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      VCR_TURN_OFF: true
      SECRET_PLANET_TOKEN: ${{ secrets.SECRET_PLANET_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
```

```{r eval=FALSE}
test_that("get_packages2() works", {
  vcr::use_cassette("packages2", {
    pkgs <- get_packages2("maelle")
  })
  expect_vector(pkgs, character())
})
```

Test for error

```{r eval=FALSE}
test_that("get_packages2 errors well", {
  withr::local_envvar("SECRET_PLANET_TOKEN" = "")
  expect_snapshot_error(get_packages2("maelle"))
})
```

## Custom skipper

```{r eval=FALSE}

skip_if_not_beyonce <- function() {
  user <- whoami::username()
  if (user == "beyonce") {
    return(invisible(TRUE))
  }
  skip("Not Beyonce !")
}
```

## Scheduled run

```yaml
# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 12 * * *'

name: with-auth

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
          - {os: macOS-latest, r: 'release'}
          - {os: ubuntu-20.04, r: 'release', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"}
          - {os: ubuntu-20.04,   r: 'devel', rspm: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest", http-user-agent: "R/4.1.0 (ubuntu-20.04) R (4.1.0 x86_64-pc-linux-gnu x86_64 linux-gnu) on GitHub Actions" }

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      VCR_TURN_OFF: true
      SECRET_PLANET_TOKEN: ${{ secrets.SECRET_PLANET_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}

      - uses: r-lib/actions/setup-pandoc@v1

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Restore R package cache
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          while read -r cmd
          do
            eval sudo $cmd
          done < <(Rscript -e 'writeLines(remotes::system_requirements("ubuntu", "20.04"))')

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          remotes::install_cran("rcmdcheck")
        shell: Rscript {0}

      - name: Check
        env:
          _R_CHECK_CRAN_INCOMING_REMOTE_: false
        run: |
          options(crayon.enabled = TRUE)
          rcmdcheck::rcmdcheck(args = c("--no-manual", "--as-cran"), error_on = "warning", check_dir = "check")
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check

```