---
title: Further resources
weight: 1000
chapter: false
slides: false
menuTitle: Resources
output: hugodown::md_document
---

## Testing, HTTP testing

* [rOpenSci dev guide, testing recommendations](https://devguide.ropensci.org/building.html#testing)
* [HTTP testing book](https://books.ropensci.org/http-testing)
* [R-hub blog post about mocking](https://blog.r-hub.io/2019/10/29/mocking/)
* [R-hub blog post about helper code and files for your testthat tests](https://blog.r-hub.io/2020/11/18/testthat-utility-belt/)
* [Vignette about testthat third edition](https://testthat.r-lib.org/articles/third-edition.html), [webinar about testthat third edition](https://www.rstudio.com/resources/webinars/testthat-3/).


## R package development

* [R Packages book](https://r-pkgs.org) by Hadley Wickham and Jenny Bryan

* [Shannon Pileggi's "Your first R package in 1 hour"](https://www.pipinghotdata.com/posts/2020-10-25-your-first-r-package-in-1-hour/)

* [Jim Hester's talk "You can make a package in 20 minutes"](https://www.jimhester.com/talk/2018-rsc-r-pkgs/)

* [rOpenSci dev guide](https://devguide.ropensci.org)

* [Tidyverse design guide](https://design.tidyverse.org/)

* [R-hub blog](https://blog.r-hub.io)

* [Writing R Extensions](https://cran.r-project.org/doc/manuals/R-exts.html) (one piece at a time)

* [Advanced R](https://adv-r.hadley.nz/) by Hadley Wickham

* My own blog post with many links to fantastic resources: ["How to develop good R packages"](http://www.masalmon.eu/2017/12/11/goodrpackages/)

## Continuous integration in particular

* [A Beginner's Guide to Travis-CI for R](https://juliasilge.com/blog/beginners-guide-to-travis/) by Julia Silge

* [GitHub Actions for R](https://www.jimhester.com/talk/2020-rsc-github-actions/) by Jim Hester

## CRAN submissions

* [You CRAN Do It](https://ivelasq.rbind.io/blog/you-cran-do-it/) by Isabella Velásquez (including a link to other resources at the end)

## From scripts to package

* [prefixer package](https://github.com/dreamRs/prefixer), "Prefix function with their namespace".

* [sinew package](https://yonicd.github.io/sinew/articles/motivation.html)

## Things we saw in my .Rprofile

`r hugodown::embed_tweet("1202269314029621251")`

* [reprex](https://reprex.tidyverse.org/)

* [lookup](https://github.com/jimhester/lookup#readme), [related R-hub blog post](https://blog.r-hub.io/2019/05/14/read-the-source/)
